version: 1.0.{build}
branches:
  only:
  - master
environment:
  COVERALLS_REPO_TOKEN:
    secure: xlR3CnYajEuet3ZdyDZpxYHT/+rvug8RjGT9mHzEv3foysoATeaa7nevl12gDoed
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
build:
  project: TestPlatform.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
after_test:
- cmd: >-
    packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml -r %COVERALLS_REPO_TOKEN%